---
title: "GPS Matching"
author: "Ben Weinstein"
date: "May 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
library(stringr)
library(ggplot2)
library(plotKML)
library(reshape2)
library(maptools)
library(dplyr)

#get waypoints
basename="C:/Users/Ben/Dropbox/Ecuador hummingbird project/Public Folder/Data"

allwaypoints<-list.dirs(basename,recursive=TRUE,full.name=TRUE)
allwaypoints<-allwaypoints[str_detect(allwaypoints,"waypoints")]
```

```{r}
#read in waypoints
x<-allwaypoints[1]
wayfiles<-function(x){
  #get files
  
  f<-list.files(x,pattern=".gpx",recursive=TRUE,full.names=T)
  
  gpx_files<-lapply(f,function(y){
    out<-list()
    for(j in 1:length(y)){
      try(out[[j]]<-readGPX(y[j],waypoints=TRUE)$waypoints)
    }
    out<-do.call("rbind",out)
    
    return(out)
  })
  gpx_files<-do.call("rbind",gpx_files)
  
  #get folder name
  gpx_files$Site<-str_match(f,"(\\w+)/waypoints")[2]
  return(gpx_files)

}
way_sites<-lapply(allwaypoints,wayfiles)

#remove empty lists
way_sites<-way_sites[sapply(way_sites,length) >0]
way_sites<-bind_rows(way_sites)
```

Create Date field

```{r}
way_sites$Date<-sapply(way_sites$time,function(x){
  b<-strsplit(as.character(x),"T")[[1]][1]
  if(is.na(b)){
    return("S")
  }
  return(format(as.POSIXlt(b),"%Y-%m-%d"))
})
```

Standardize time field


```{r}
way_sites$Time<-sapply(way_sites$time,function(x){
  b<-strsplit(as.character(x),"T")[[1]][2]
  #remove the z
  b<-strsplit(as.character(b),"Z")[[1]][1]
  timet<-format(strptime(b,"%H:%M:%S"),"%H:%M:%S")
  return(timet)
})
```

#Create combined ID for each waypoint

```{r}
way_sites$ID<-paste(way_sites$Site,"_",way_sites$name,sep="_")

#Select columns
way_sites<-way_sites %>% select(ID,lon,lat,ele,Date,Time,Site,name)

#write gps points
write.csv("C:/Users/Ben/Dropbox/Ecuador hummingbird project/Public Folder/Data/Cleaned/GPS.csv")

#Write in case we want to visualize with the shiny data
write.csv("HummingbirdData/GPS.csv")
```


